Play travis
Otus-DevOps-2018-11/ivan-kamenskiy_infra pull request #1
Opened 2019-01-01 13:47 UTC by ivan-kamenskiy

2019-01-02 15:28 UTC, mrgreyves requested changes
Здравствуйте! Добавьте пожалуйста описание к пуллреквесту!)

2019-01-03 11:25 UTC, ivan-kamenskiy commented
add .travis.yml, test.py, PULL_REQUEST_TEMPLATE.md

2019-01-03 11:27 UTC, mrgreyves commented
Спасибо!) В файле с тестами у вас ошибка, указал в каком именно месте. Исправьте пожалуйста)

2019-01-03 13:36 UTC, ivan-kamenskiy commented
Сделал правку test.py

2019-01-03 14:20 UTC, mrgreyves approved these changes
Спасибо! ДЗ принимаю!)

2019-01-03 14:20 UTC, mrgreyves commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
Ошибочка)

2019-01-04 09:07 UTC, merged